// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by running:
// flutter pub run build_runner build --delete-conflicting-outputs

import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

// TODO: Add @Injectable() annotations to your use cases, repositories, and data sources.

GetIt getIt = GetIt.instance;

@InjectableInit()
void init() {
  // This will be filled by injectable codegen
}
